# secrets.toml - TEMPLATE (NO SUBIR AL REPOSITORIO)
# Copia este contenido a Streamlit Cloud → Settings → Secrets

[firebase]
# Si usas Firebase, agrega aquí tus credenciales
project_id = "tu-project-id"
private_key = "-----BEGIN PRIVATE KEY-----\nTU_PRIVATE_KEY_AQUI\n-----END PRIVATE KEY-----"
client_email = "tu-service-account@tu-project.iam.gserviceaccount.com"

[model]
# Configuraciones del modelo
max_predictions = 5
confidence_threshold = 0.1

[app]
# Configuraciones de la app
max_file_size_mb = 10
